import { createFileRoute } from "@tanstack/react-router";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const Route = createFileRoute("/privacy-policy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy: AI to the Summit" },
      {
        name: "description",
        content:
          "How AI to the Summit handles account details, location data, chat messages and locally stored safety information, and which third party services process them.",
      },
      { property: "og:title", content: "Privacy Policy: AI to the Summit" },
      {
        property: "og:description",
        content:
          "What data AI to the Summit collects, how location and chat information is used, and which third party providers are involved.",
      },
      { property: "og:type", content: "article" },
      { property: "og:url", content: "https://ai-summit-mountain.lovable.app/privacy-policy" },
      { name: "twitter:card", content: "summary" },
    ],
    links: [{ rel: "canonical", href: "https://ai-summit-mountain.lovable.app/privacy-policy" }],
  }),
  component: PrivacyPolicyPage,
});

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-display text-xl font-bold mb-3">{title}</h2>
      <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">{children}</div>
    </section>
  );
}

function PrivacyPolicyPage() {
  return (
    <div className="relative min-h-screen overflow-x-hidden">
      <Navbar />
      <main className="relative z-10 pt-32 pb-20">
        <div className="container mx-auto px-6 max-w-3xl">
          <h1 className="font-display text-3xl md:text-4xl font-bold mb-3">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground mb-10">
            This policy explains what AI to the Summit collects, why, and who else processes it.
          </p>

          <Section title="Information we collect">
            <p>
              Account information: when you register we store the email address, display name and
              authentication identifiers needed to sign you in. Passwords are handled by our
              authentication provider and are never visible to us.
            </p>
            <p>
              Location data: the triage and trail features read your coordinates from your device
              only after you grant permission in the browser. Coordinates are used to look up a
              place name, elevation and current weather, and to build an emergency report you can
              share. You can refuse or revoke this permission at any time in your browser settings.
            </p>
            <p>
              Messages: text you send to the assistant is transmitted to an AI model provider to
              generate a reply.
            </p>
            <p>
              Local device storage: survival checklists and draft emergency messages are saved in
              your browser's local storage so they remain available without a signal. They stay on
              your device and are not uploaded.
            </p>
          </Section>

          <Section title="Cookies and similar technologies">
            <p>
              We use cookies and browser storage that are necessary for the site to function,
              primarily to keep you signed in. We do not use advertising cookies. If analytics are
              enabled in future, this page will be updated before they are introduced.
            </p>
          </Section>

          <Section title="Third party services">
            <p>
              Hosting, database and authentication are provided by our cloud backend provider.
              Assistant replies are generated by a third party AI model provider. Place names come
              from the OpenStreetMap Nominatim service, elevation from Open Elevation, and weather
              from Open Meteo. These providers receive only the data needed to answer the request,
              such as a coordinate pair or your message text.
            </p>
          </Section>

          <Section title="How we use the data">
            <p>
              To operate and secure your account, to answer your questions, to produce location
              aware guidance and weather information, and to generate emergency summaries at your
              request. We do not sell personal data.
            </p>
          </Section>

          <Section title="Retention">
            <p>
              Account records are kept while your account is active. Location readings used for a
              single lookup are not retained as a history. Data stored in your browser remains until
              you clear it or use the in app clear action.
            </p>
          </Section>

          <Section title="Your choices">
            <p>
              You may request access to, correction of, or deletion of your account data. You can
              deny location access and still use the informational and offline sections of the site.
            </p>
          </Section>

          <Section title="Security">
            <p>
              Access to stored data is restricted by row level database policies and encrypted
              transport. No method of transmission over the internet is completely secure, so we
              cannot guarantee absolute security.
            </p>
          </Section>

          <Section title="Children">
            <p>
              The service is not directed at children under 13, and we do not knowingly collect
              their personal information.
            </p>
          </Section>

          <Section title="Changes to this policy">
            <p>
              We may update this policy as the product changes. Material changes will be reflected
              on this page.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Privacy requests: [add your contact email address here]. This is a placeholder and
              should be replaced with a monitored address before launch.
            </p>
          </Section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
